src/components/LoginForm/loginform.js, src/components/MapForm/mapform.js, src/components/SignupForm/signupform.js, src/utils/API.js
user can create a new user d
user can login 
user can create a new map
*caveat, the user can't create a map with their session id, still need to debug
=> Ner auth integration

src/pages/Suggestion/Suggestion.js
small fix to import for suggestion page so that react app could render
=> fixed connectivity for suggestion page

src/components/DashModule/dashmod.css, src/components/DashModule/dashmod.js, src/components/LoginForm/loginform.css, src/components/MapCard/mapcard.js
Module Built Out. 
Pending:
- Connection to DB data. 
- Comments section
=> Vin dashboard build out

src/utils/API.js
added withCredentials : true to chats and suggestions api
=> added withcredentials true to suggestions and chats

src/components/Chat/chat.css, src/components/Chat/chat.js, src/components/MapCard/mapcard.css, src/components/MapCard/mapcard.js, src/pages/MapDashboard/MapDashboard.js
=> Vin Front Dataflow

src/components/SuggestionCard/SuggestionCard.js, src/components/UserCard/UserCard.js, src/components/UserCard/usercard.css, src/components/suggestionForm/suggestionForm.js
=> Added modal for user page

package.json, src/utils/API.js
=>  heroku config

src/pages/Suggestion/Suggestion.js
adjusting suggestionForm folder
=> adjusting suggestionForm folder

src/components/Chat/chat.js
=> Zb dpostdeploy

src/utils/API.js
- changed addNewMap route to pass dates in correct format
- added new routes to API for change user's name, email and user invites accept/decline routes
=> Djw invites change user info

src/App.js, src/components/LoginForm/loginform.css, src/components/PageDivider/pagedivider.css, src/components/PageDivider/pagedivider.js, src/components/UX Instructions/uxinstructions.css, src/components/UX Instructions/uxinstructions.js
Debugged home page styling/responsiveness
=> Vin Frontend

src/components/SuggestionCard/SuggestionCard.js, src/utils/API.js
comments are working
like button modal working
=> Ner comments

src/components/FinalRenderCard/FinalRenderCard.js, src/components/FinalRenderColumns/CardColumns.js
=> Btp logic itinerary

src/components/NavBar/navbar.js, src/components/SuggestionCard/SuggestionCard.js, src/pages/MapDashboard/MapDashboard.js, src/utils/API.js
user can only vote once working
=> Ner modals 1

src/components/Chat/chat.js, src/utils/API.js
created auto scroll for chat so when new chats come in it will scroll to bottom of the div automatically
=> Zb dpostworkingchat

src/components/UserCard/UserCard.js, src/components/UserCard/usercard.css
Add new map button to user page
=> adding new map button to user page

src/components/CarouselContent/CarouselContent.js, src/components/FinalRenderCard/FinalRenderCard.js, src/components/NavBar/navbar.js
popconfirm on email final itinerary
=> popconfirm on email final interary

src/components/Chat/chat.js, src/utils/API.js
=> heroku set up

src/components/Chat/chat.css, src/components/FinalRenderCard/FinalRenderCard.js, src/components/MapCard/mapcard.js, src/components/PhotoUpload/photoupload.css, src/components/PhotoUpload/photoupload.js, src/components/UserCard/UserCard.js, src/components/suggestionForm/suggestionForm.js, src/pages/MapDashboard/MapDashboard.js, src/utils/API.js
=> Ner images

src/components/Chat/chat.js, src/components/LandingContent/landingcontent.css, src/components/LandingContent/landingcontent.js, src/utils/API.js
added still home page image for smaller devices
=> Home Page Image

src/components/NavBar/navbar.css, src/components/NavBar/navbar.js, src/components/UserCard/UserCard.js, src/components/UserCard/usercard.css, src/pages/User/User.js, src/utils/API.js
- added some styling to image display in navbar and user page
- made the most recently uploaded image be the one that displays in those places
- users can now change their current pic with this method
- added a placeholder image that uses user initials when a user has not yet uploaded an image
=> changed up how profile images are displayed in navbar and on user page

src/App.js, src/components/LandingContent/landingcontent.css, src/components/LandingContent/landingcontent.js, src/components/Loading/loading.css, src/components/Loading/loading.js, src/components/MapCard/mapcard.css, src/components/NavBar/navbar.css, src/components/NavBar/navbar.js, src/components/PageDivider/pagedivider.css, src/components/PageDivider/pagedivider.js, src/components/PhotoUpload/photoupload.css, src/components/PhotoUpload/photoupload.js, src/components/UserCard/UserCard.js, src/pages/Home/Home.js
- Loading screen for home page
- Still home image for smaller devices
- Snap scroll transition adjustment
- Photo gallery within photo upload modal
- Placement styling for avatar photo
=> Vin Updates

src/components/LoginForm/loginform.css, src/components/LoginForm/loginform.js, src/utils/API.js
- created new form on login for forgotten password
- made API function to send email
- made form submit call api function
=> created form and function to reset user password with email

src/components/Loading/loading.js
=> Vin _ Loading Updates

src/components/Chat/chat.js, src/utils/API.js
=> Setting up deploy
